export const UPDATE_TRENDING_ORDER_BY = 'UPDATE_TRENDING_ORDER_BY';
export const UPDATE_ADD_LIST_ORDERED = 'UPDATE_ADD_LIST_ORDERED';
export const UPDATE_ADD_LIST_PRIVACY = 'UPDATE_ADD_LIST_PRIVACY';
export const UPDATE_ADD_LIST_SELECTED_CATEGORY =
  'UPDATE_ADD_LIST_SELECTED_CATEGORY';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
